package com.bisha.ijvm.model;

/**
 * Data Transfer Object (DTO) representing the complete execution state
 * of the MIC-1 ALU after processing a single instruction.
 *
 * <p>This immutable class captures all relevant state information for
 * one ALU operation cycle, including register values, ALU result, and
 * execution metadata. It provides multiple formatting options for
 * displaying register values in decimal, hexadecimal, and binary formats.</p>
 *
 * <h2>State Components:</h2>
 * <ul>
 *   <li><b>IR (Instruction Register):</b> The 6-bit control word (0-63)</li>
 *   <li><b>PC (Program Counter):</b> Current instruction number (starting from 1)</li>
 *   <li><b>A, B:</b> Effective register values after bus enable and inversion</li>
 *   <li><b>S (Result):</b> 32-bit ALU output after full addition</li>
 *   <li><b>vaiUm (Carry-out):</b> Carry generated by the full adder (0 or 1)</li>
 * </ul>
 *
 * <h2>Value Transformations:</h2>
 * <p>The effective A and B values (stored in this class) represent the
 * values after applying ENA/ENB (bus enables) and INVA (inversion) but
 * before the logic unit operation. These are the actual values the ALU
 * operates on, which may differ from the original register values.</p>
 *
 * <h2>Formatting Methods:</h2>
 * <ul>
 *   <li>{@link #getAHex()}, {@link #getBHex()}, {@link #getSHex()} - 8-character hex (e.g., "FFFFFFFF")</li>
 *   <li>{@link #getABin()}, {@link #getBBin()}, {@link #getSBin()} - 32-character binary strings</li>
 *   <li>{@link #getIRBin()} - 6-character binary string</li>
 *   <li>{@link #toString()} - Human-readable summary</li>
 * </ul>
 *
 * @author Miguel Mochizuki Silva
 * @author Mateus C. Dias
 * @author Joaquim Germano Félix
 * @author Gabriel Bringel Gonçalves
 * @version 1.0
 * @since 1.0
 */
public class EstadoULA {
    private final int ir;
    private final int pc;
    private final int a;
    private final int b;
    private final int s;
    private final int vaiUm;

    /**
     * Constructs an immutable ALU execution state record.
     *
     * <p>All parameters are stored directly without modification. The
     * A and B parameters should represent the <b>effective</b> register
     * values after applying bus enables and inversion, not the raw register
     * inputs. These are the values that were actually used in the ALU
     * operation.</p>
     *
     * @param ir The 6-bit instruction register value (0-63)
     * @param pc The program counter value for this instruction (1-indexed)
     * @param a Effective A register value after ENA and INVA processing
     * @param b Effective B register value after ENB processing (never inverted)
     * @param s ALU result after logic unit and full addition (32-bit)
     * @param vaiUm Carry-out from full adder (0 or 1, 1 indicates overflow beyond 32 bits)
     */
    public EstadoULA(int ir, int pc, int a, int b, int s, int vaiUm) {
        this.ir = ir;
        this.pc = pc;
        this.a = a;
        this.b = b;
        this.s = s;
        this.vaiUm = vaiUm;
    }

    /**
     * Returns the instruction register value.
     *
     * @return The 6-bit control word as an integer (0-63)
     */
    public int getIr() { return ir; }

    /**
     * Returns the program counter value.
     *
     * @return The 1-indexed instruction number in the execution sequence
     */
    public int getPc() { return pc; }

    /**
     * Returns the effective A register value.
     *
     * @return 32-bit signed integer representing the A value after ENA/INVA processing
     */
    public int getA() { return a; }

    /**
     * Returns the effective B register value.
     *
     * @return 32-bit signed integer representing the B value after ENB processing
     */
    public int getB() { return b; }

    /**
     * Returns the ALU result.
     *
     * @return 32-bit signed integer representing the ALU output S
     */
    public int getS() { return s; }

    /**
     * Returns the carry-out from the full adder.
     *
     * @return 0 or 1, where 1 indicates overflow beyond the 32nd bit
     */
    public int getVaiUm() { return vaiUm; }

    /**
     * Returns the effective A register value as an 8-digit hexadecimal string.
     *
     * <p>Example: 0xFFFFFFFF (decimal -1) → "FFFFFFFF"</p>
     *
     * @return Zero-padded uppercase hexadecimal representation (8 characters)
     */
    public String getAHex() { return String.format("%08X", a); }

    /**
     * Returns the effective B register value as an 8-digit hexadecimal string.
     *
     * <p>Example: 0x00000001 (decimal 1) → "00000001"</p>
     *
     * @return Zero-padded uppercase hexadecimal representation (8 characters)
     */
    public String getBHex() { return String.format("%08X", b); }

    /**
     * Returns the ALU result S as an 8-digit hexadecimal string.
     *
     * <p>Example: 0xFFFFFFFE (decimal -2) → "FFFFFFFE"</p>
     *
     * @return Zero-padded uppercase hexadecimal representation (8 characters)
     */
    public String getSHex() { return String.format("%08X", s); }

    /**
     * Returns the instruction register as a 6-character binary string.
     *
     * <p>Example: 60 (decimal) → "111100"</p>
     *
     * @return Zero-padded binary string with exactly 6 characters
     */
    public String getIRBin() {
        return String.format("%6s", Integer.toBinaryString(ir)).replace(' ', '0');
    }

    /**
     * Returns the effective A register as a 32-character binary string.
     *
     * <p>Example: -1 (0xFFFFFFFF) → "11111111111111111111111111111111"</p>
     *
     * @return Zero-padded binary string with exactly 32 characters
     */
    public String getABin() {
        return String.format("%32s", Integer.toBinaryString(a & 0xFFFFFFFF)).replace(' ', '0');
    }

    /**
     * Returns the effective B register as a 32-character binary string.
     *
     * <p>Example: 1 → "00000000000000000000000000000001"</p>
     *
     * @return Zero-padded binary string with exactly 32 characters
     */
    public String getBBin() {
        return String.format("%32s", Integer.toBinaryString(b & 0xFFFFFFFF)).replace(' ', '0');
    }

    /**
     * Returns the ALU result S as a 32-character binary string.
     *
     * <p>Example: -2 (0xFFFFFFFE) → "11111111111111111111111111111110"</p>
     *
     * @return Zero-padded binary string with exactly 32 characters
     */
    public String getSBin() {
        return String.format("%32s", Integer.toBinaryString(s & 0xFFFFFFFF)).replace(' ', '0');
    }

    /**
     * Returns a human-readable summary of the ALU execution state.
     *
     * <p>Format: "PC=1, IR=111100, A=FFFFFFFF, B=00000001, S=FFFFFFFE, VaiUm=0"</p>
     *
     * @return Formatted string containing PC, IR (binary), A, B, S (hex), and carry-out
     */
    @Override
    public String toString() {
        return String.format("PC=%d, IR=%s, A=%08X, B=%08X, S=%08X, VaiUm=%d",
            pc, getIRBin(), a, b, s, vaiUm);
    }
}
